---
- hosts: kubernetes-worker-nodes
  vars_files:
  - env_variables
  tasks:
  - name: Copy join command from Ansiblehost to the worker nodes
    become_user: yes
    copy:
      src: /tmp/kubernetes_join_command
      dest: /tmp/kubernetes_join_command
      mode: 0777
    delegate_to: k8s-dev-master

  - name: Join the Worker nodes to the cluster
    command: sh /tmp/kubernetes_join_command
    register: joined_or_not

  - name: Copying token to worker nodes
    copy: src={{ token_file }} dest=join_token

  - name: Joining worker nodes with kubernetes master
    shell: "`grep -i 'kubeadm join' join_token`"

